name: Terraform CI

on:
  pull_request:
    branches:
      - main

jobs:
  terraform:
    name: Terraform Format, Init, Validate & Plan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    defaults:
      run:
        shell: bash

    env:
      AWS_REGION: us-east-1
      TF_IN_AUTOMATION: true

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.15.8

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Verify AWS Credentials
        run: |
          aws --version
          aws sts get-caller-identity

      - name: Terraform Version
        run: terraform version

      - name: Terraform Format Check
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: infra/envs/dev
        run: terraform init -reconfigure

      - name: Terraform Validate
        working-directory: infra/envs/dev
        run: terraform validate

      - name: Show Terraform Files
        working-directory: infra/envs/dev
        run: |
          pwd
          ls -la

      - name: Terraform Plan
        working-directory: infra/envs/dev
        run: |
          terraform plan \
            -input=false \
            -lock=false \
            -refresh=false \
            -no-color \
            -out=tfplan

          terraform show -no-color tfplan > plan_output.txt

      - name: Upload Terraform Plan
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: terraform-plan
          path: infra/envs/dev/plan_output.txt
